### PR TITLE
GQL

### PR DESCRIPTION
**Pull request by kaskranenburgQ**
Improves GQL function INVALID_TO_ZERO

Goes together with PR [Add GQL documentation #178](https://github.com/quintel/documentation/pull/178#issuecomment-2042040247)

### CODE REVIEW

**Comment by mabijkerk** [comment]
I have not seen this GQL function being used in any gqueries and I was not familiar with it myself. Unless if we can come up with a relevant use case, I would conclude that we should remove this GQL instead. Do you agree @kaskranenburgQ? Can we simply remove a GQL function @noracato?

**Comment by kaskranenburgQ** [comment]
I think this function could be useful if you are preparing data.
I don't think it is therefore necessary in GQL, since with our use of the language no data needs to be prepared. 
Removing instead of fixing the function would be a better idea in that case.

**Comment by noracato** [comment]
> Can we simply remove a GQL function @noracato?

If it's not used in any queries, you should be safe to remove it. Make sure to check the `specs` to see if you should also remove the tests for it!

> Removing instead of fixing the function would be a better idea in that case.

Agreed! Always nice when we can declutter!

**Comment by mabijkerk** [comment]
@kaskranenburgQ can you remove the GQL function and any accompanying specs from ETEngine and the documenation?

**Pull request merged**
