### PR TITLE
Update scenario inputs to reflect industry changes

### PR DESCRIPTION
**Pull request by antw**
### :fire: Do not merge! :fire:

--

@jorisberkhout @RobTerwel This is the migration to update scenario inputs to reflect the recent industry changes. The migration does successfully complete (albeit it takes 15-20 minutes to run against 400k beta scenarios), however before merging I'd like it if there were some way to validate that the numbers are correct. I'm not sure how we'd go about doing that...

Maybe if there were a couple of sample scenarios where I could provide before-and-after values for you to check? That's easier said than done since the industry changes are already on beta (shouldn't really have been merged until scenarios and presets were updated, but that's water under the bridge).

### CODE REVIEW

**Comment by antw** [comment]
Also, I've just realised that the Excel file documenting the migration – and the migration itself – name a number of inputs which do not currently exist in ETSource; is this intentional? Maybe some were just misnamed?

* industry_useful_demand_for_other_food_electricity_efficiency
* industry_useful_demand_for_other_paper_electricity_efficiency
* industry_useful_demand_for_other_aggregated_industry_nl_electricity_efficiency
* industry_useful_demand_for_other_aggregated_industry_other_electricity_efficiency
* industry_useful_demand_for_other_food_useable_heat_efficiency
* industry_useful_demand_for_other_paper_useable_heat_efficiency
* industry_useful_demand_for_other_aggregated_industry_nl_useable_heat_efficiency
* industry_useful_demand_for_other_aggregated_industry_other_useable_heat_efficiency

**Comment by RobTerwel** [comment]
> Maybe if there were a couple of sample scenarios where I could provide before-and-after values for you to check?

We could manually compute the new slider values for a couple of scenario's (say Urgenda / SER 2020/2023) and validate the results with those values. What do you think, @jorisberkhout ?

As to the list of inputs, you are right:

> industry_useful_demand_for_other_food_electricity_efficiency
industry_useful_demand_for_other_paper_electricity_efficiency
industry_useful_demand_for_other_aggregated_industry_nl_electricity_efficiency
industry_useful_demand_for_other_aggregated_industry_other_electricity_efficiency
industry_useful_demand_for_other_food_useable_heat_efficiency
industry_useful_demand_for_other_paper_useable_heat_efficiency
industry_useful_demand_for_other_aggregated_industry_nl_useable_heat_efficiency
industry_useful_demand_for_other_aggregated_industry_other_useable_heat_efficiency

should be

``
industry_useful_demand_for_other_food_efficiency
industry_useful_demand_for_other_paper_efficiency
industry_useful_demand_for_other_aggregated_industry_nl_efficiency
industry_useful_demand_for_other_aggregated_industry_other_efficiency
``

Thanks for spotting this! I'll send you an updated version of the migration excel.

**Comment by RobTerwel** [comment]
> We could manually compute the new slider values for a couple of scenario's (say Urgenda / SER 2020/2023) and validate the results with those values. 

The `scenario_id` of (staging) scenario's for which I'd like to check the migration manually are
- 155680 (Urgenda)
- 507792 (Gelderland, scaled scenario)
- 423882 (RLI 95%)

@antw , could you send me the changes (i.e., `user_values` before and after) in these scenario's once you've performed the migration?

**Comment by antw** [comment]
**[Here are the three updated scenarios, as requested]( https://gist.github.com/antw/d57f0b1916d363568102269412f2784a)**. If you click "Revisions" in the header, you'll be presented with [a diff, describing only the changes which were made](https://gist.github.com/antw/d57f0b1916d363568102269412f2784a/revisions); you might find that easier to read.

**Comment by RobTerwel** [comment]
> Here are the three updated scenarios, as requested. 

Thanks, I'll compare them right away.

**Comment by RobTerwel** [comment]
I had a look and everything seems to have work as expected except for three things:

 - The new useful demand for the other industry is calculated incorrectly.

The migration now yields `industry_useful_demand_for_other_food = 1.0` instead of `144.51` for scenario 423882. The entries of lines <a href="https://gist.github.com/antw/d57f0b1916d363568102269412f2784a/revisions#diff-1ee6a60729c43cdf8431aaf260187192L252">252 and 254-256</a> are all 1. Plugging those entries in the formula

`
=(1+AVERAGE(252,254-256)/100)^(end_year-base_year)*100 = (1+1/100)^(37)*100 = 144.507647
`

What comes out, however is a new entry of <a href="https://gist.github.com/antw/d57f0b1916d363568102269412f2784a/revisions#diff-1ee6a60729c43cdf8431aaf260187192R273">1.0</a>. The same happens for scenario 155680 in spite of having different initial input values, so this suggests the method might 'always' return 1.0


- The efficiency slider migration yields the wrong names

As mentioned in https://github.com/quintel/etengine/pull/858#issuecomment-238788965 above, the efficiency slider migration gave the wrong names initially. The correct ones are at the bottom of the post (please also see the latest excel file I sent you). To give an example of what happens, the initial slider efficiency setting for the other industry in 155680 was <a href="https://gist.github.com/antw/d57f0b1916d363568102269412f2784a/revisions#diff-d04409b41b5f5ab4444757570989b698L247">industry_useful_demand_for_other_electricity_efficiency = 2.0</a>. After the migration we get <a href="https://gist.github.com/antw/d57f0b1916d363568102269412f2784a/revisions#diff-d04409b41b5f5ab4444757570989b698R248">industry_useful_demand_for_other_food_electricity_efficiency = 2.0</a>. There should no longer be `_electricity` in the latter statement. In addition, but this is probably linked to keeping the electricity and useable_heat efficiency separated, the new efficiency should be 1.0 (the average of 2.0 and 0.0, the input values for `industry_useful_demand_for_other_food_electricity_efficiency` and `industry_useful_demand_for_other_food_usable_heat_efficiency`, respectively).

- Some old inputs are not deleted after the migration.

Several inputs are migrated correctly, but the old inputs are not deleted. The following inputs should be deleted *after* the migration.

`industry_final_demand_steam_hot_water_share`
`industry_useful_demand_for_chemical_useable_heat`
`industry_useful_demand_for_chemical_other_non_energetic`
`industry_final_demand_steam_hot_water_share_present`
`industry_useful_demand_for_chemical_useable_heat_both`
`industry_useful_demand_for_chemical_other_non_energetic_both`

**Comment by antw** [comment]
Thanks for the sanity check, @RobTerwel. I'll look into those issues shortly and will report back.

**Comment by antw** [comment]
I managed to make a mess of the original Gist, so I created a new one.

**[Here are the updated scenario inputs](https://gist.github.com/antw/2b57552964a01b2093d9bb56f438a741)**. As before [a diff is available](https://gist.github.com/antw/6c960261b2d1b9c0e10f13509006f150/revisions).

**Comment by RobTerwel** [comment]
> Here are the updated scenario inputs.

The results of this migration turn out exactly as expected for these scenario's! Great job! 🎉 

@antw and @jorisberkhout , are there any other scenario's you'd like to see tested before we perform the 'final' migration?

**Comment by jorisberkhout** [comment]
> @antw and @jorisberkhout , are there any other scenario's you'd like to see tested before we perform the 'final' migration?

Not for me. One question though, does this migration work for the preset scenario's as well? Or do we need to update those manually?

**Comment by antw** [comment]
> One question though, does this migration work for the preset scenario's as well? Or do we need to update those manually?

It updates user scenarios in the database only. With some minor modifications I should be able to use it with Atlas to update the ETSource presets.

**Comment by jorisberkhout** [comment]
> With some minor modifications I should be able to use it with Atlas to update the ETSource presets.

If you have time to do that, that would be much appreciated. Let me know if I can help you with anything.

**Pull request closed without merging**
